new-session -n $HOST
# Copied from: https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# I am keeping the linux keybinding to C-b so that I can use the Linux tmux when I am sshing from the mac tmux.
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
# https://stackoverflow.com/questions/38543763/tmux-will-not-stop-auto-renaming-windows
set -g allow-rename off
